parameters:
    creonit_admin.component.field.default.class: Creonit\AdminBundle\Component\Field\Field
    creonit_admin.component.field.external.class: Creonit\AdminBundle\Component\Field\ExternalField
    creonit_admin.component.field.date.class: Creonit\AdminBundle\Component\Field\DateField
    creonit_admin.component.field.file.class: Creonit\AdminBundle\Component\Field\FileField
    creonit_admin.component.field.image.class: Creonit\AdminBundle\Component\Field\ImageField
    creonit_admin.component.field.video.class: Creonit\AdminBundle\Component\Field\VideoField
    creonit_admin.component.field.gallery.class: Creonit\AdminBundle\Component\Field\GalleryField
    creonit_admin.component.field.select.class: Creonit\AdminBundle\Component\Field\SelectField
    creonit_admin.component.field.checkbox.class: Creonit\AdminBundle\Component\Field\CheckboxField
    creonit_admin.component.field.content.class: Creonit\AdminBundle\Component\Field\ContentField

services:
    creonit_admin:
        class: Creonit\AdminBundle\Manager
        arguments:
            - '@service_container'
            - '@templating'

    creonit_admin.component.scope.default:
        class: Creonit\AdminBundle\Component\Scope\Scope
        shared: false

    creonit_admin.component.scope.table_row:
        class: Creonit\AdminBundle\Component\Scope\TableRowScope
        shared: false


    creonit_admin.component.field:
        abstract: true
        arguments: ['@service_container']

    creonit_admin.component.field.default:
        class: '%creonit_admin.component.field.default.class%'
        parent: creonit_admin.component.field
        shared: false

    creonit_admin.component.field.external:
        class: '%creonit_admin.component.field.external.class%'
        parent: creonit_admin.component.field
        shared: false

    creonit_admin.component.field.date:
        class: '%creonit_admin.component.field.date.class%'
        parent: creonit_admin.component.field
        shared: false

    creonit_admin.component.field.file:
        class: '%creonit_admin.component.field.file.class%'
        parent: creonit_admin.component.field
        shared: false

    creonit_admin.component.field.image:
        class: '%creonit_admin.component.field.image.class%'
        parent: creonit_admin.component.field
        shared: false

    creonit_admin.component.field.video:
        class: '%creonit_admin.component.field.video.class%'
        parent: creonit_admin.component.field
        shared: false

    creonit_admin.component.field.gallery:
        class: '%creonit_admin.component.field.gallery.class%'
        parent: creonit_admin.component.field
        shared: false

    creonit_admin.component.field.select:
        class: '%creonit_admin.component.field.select.class%'
        parent: creonit_admin.component.field
        shared: false

    creonit_admin.component.field.checkbox:
        class: '%creonit_admin.component.field.checkbox.class%'
        parent: creonit_admin.component.field
        shared: false

    creonit_admin.component.field.content:
        class: '%creonit_admin.component.field.content.class%'
        parent: creonit_admin.component.field
        shared: false